### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
	"name":"lanre irewole",
	"company":"gomom ltd",
	"address":"plot 1004 lagos",
	"phone":"080111111",
	"email":"lanre@lanre.com",
	"password":"123456$$$"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
	"email":"lanre@lanre.com",
	"password":"password1"
}

### Get A user profile
GET http://localhost:3001/v1/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMDQ2MzEwMiwiZXhwIjoxNjMwNDY0MDAyfQ.eK358yNoVQeWCOJkzY9XOjKBdTl1AdWSJrRRKtpfICY

### GET refreshed token

GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMDY0MTczMiwiZXhwIjoxNjMzMjMzNzMyfQ.HxtQQN_iW4E0AveXtGzVhDYOi4OgEae5x-Q6hEC_eMI

### Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
	"email":"lanre@lanre.com"	
}

### Update New Password
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
	"email":"lanre@lanre.com",
    "pin":468818,
    "newPassword":"password1"
}


### user logout end
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMDk1NDMxMiwiZXhwIjoxNjMwOTU1MjEyfQ.PcGt0r1bQEG3Zy8p7BOxeuEyTDqth8bkZO7YKXye5Dc



### Create a new ticket
POST http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTM2Nzg0MCwiZXhwIjoxNjMxMzY4NzQwfQ.C9dfog7244iZIk6_j0lYyjnDXdnQZ_xC6UOshhAa8UA
Content-Type: application/json

{
	"subject":"Another BRT Bus Delay",
	"sender":"Lanre",
	"message":"Kindly provide buses for us here in oshodi"
}

### Get tickets for a specific user
GET http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTAzNjcwMiwiZXhwIjoxNjMxMDM3NjAyfQ.DZIvmoECh4fMmfDhMBdd9dlgk5V4fY29BPCDIn1lezM


### Get specific ticket
GET http://localhost:3001/v1/ticket/6137a53b685cb41e20eda5e7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTA0MzE4OSwiZXhwIjoxNjMxMDQ0MDg5fQ.qjHJmyEMsOI4m0QNOHgrNe_XZUzPxgNoekAxpSX11FE

### Update a ticket
PUT http://localhost:3001/v1/ticket/6138299093e013239805fe96
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTM3MTI4NiwiZXhwIjoxNjMxMzcyMTg2fQ.XOLsdbDfbRnc5G50wnwDIAjOdPFdFZy0g4bvm3CQfco
Content-Type: application/json

{
    "message":"This is testing a an update message",
    "sender":"Lanre"
}

### Update ticket to close 
PATCH http://localhost:3001/v1/ticket/close-ticket/6137959fe63d4439785011d7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTE2MDc1NiwiZXhwIjoxNjMxMTYxNjU2fQ.7g1P_lReJ78Hr3s7iWJcIJ252fsqQUuG19gV_oPjOak

Content-Type: application/json


### delete ticket
DELETE  http://localhost:3001/v1/ticket/6137959fe63d4439785011d7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTE2MjIzMywiZXhwIjoxNjMxMTYzMTMzfQ.azkbmsLf-uXHsnhsTNPsCq0cjkrFe4lUAVBo7FvXhM4

Content-Type: application/json
