### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
	"name":"lanre irewole",
	"company":"gomom ltd",
	"address":"plot 1004 lagos",
	"phone":"080111111",
	"email":"lanre@lanre.com",
	"password":"123456$$$"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
	"email":"lanre@lanre.com",
	"password":"password1"
}

### Get A user profile
GET http://localhost:3001/v1/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMDQ2MzEwMiwiZXhwIjoxNjMwNDY0MDAyfQ.eK358yNoVQeWCOJkzY9XOjKBdTl1AdWSJrRRKtpfICY

### GET refreshed token

GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMDY0MTczMiwiZXhwIjoxNjMzMjMzNzMyfQ.HxtQQN_iW4E0AveXtGzVhDYOi4OgEae5x-Q6hEC_eMI

### Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
	"email":"lanre@lanre.com"	
}

### Update New Password
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
	"email":"lanre@lanre.com",
    "pin":468818,
    "newPassword":"password1"
}


### user logout end
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMDk1NDMxMiwiZXhwIjoxNjMwOTU1MjEyfQ.PcGt0r1bQEG3Zy8p7BOxeuEyTDqth8bkZO7YKXye5Dc



### Create a new ticket
POST http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTAzNTgwMCwiZXhwIjoxNjMxMDM2NzAwfQ.wWuxTfACMsznJ2d2o9IAPpcxbXwAWZ6tiYPw-iPfdhg

### Get tickets for a specific user
GET http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTAzNjcwMiwiZXhwIjoxNjMxMDM3NjAyfQ.DZIvmoECh4fMmfDhMBdd9dlgk5V4fY29BPCDIn1lezM


### Get specific ticket
GET http://localhost:3001/v1/ticket/6137a53b685cb41e20eda5e7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMTA0MzE4OSwiZXhwIjoxNjMxMDQ0MDg5fQ.qjHJmyEMsOI4m0QNOHgrNe_XZUzPxgNoekAxpSX11FE


