### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
	"name":"lanre irewole",
	"company":"gomom ltd",
	"address":"plot 1004 lagos",
	"phone":"080111111",
	"email":"lanre@lanre.com",
	"password":"123456$$$"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
	"email":"lanre@lanre.com",
	"password":"123456$$$"
}

### Get A user profile
GET http://localhost:3001/v1/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMDQ2MzEwMiwiZXhwIjoxNjMwNDY0MDAyfQ.eK358yNoVQeWCOJkzY9XOjKBdTl1AdWSJrRRKtpfICY

### GET refreshed token

GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbnJlQGxhbnJlLmNvbSIsImlhdCI6MTYzMDY0MTczMiwiZXhwIjoxNjMzMjMzNzMyfQ.HxtQQN_iW4E0AveXtGzVhDYOi4OgEae5x-Q6hEC_eMI